[package]
name       = "cometbft-light-client"
version    = "0.34.0"
edition    = "2021"
license    = "Apache-2.0"
readme     = "README.md"
keywords   = ["blockchain", "bft", "consensus", "cosmos", "cometbft", "tendermint"]
categories = ["cryptography::cryptocurrencies", "network-programming"]
repository = "https://github.com/cometbft/cometbft-rs"
authors    = [
  "Informal Systems <hello@informal.systems>",
  "Ismail Khoffi <Ismail.Khoffi@gmail.com>",
  "Alexander Simmerl <a.simmerl@gmail.com>",
]

description = """
    Implementation of the CometBFT Light Client Verification Protocol.
"""

# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rpc-client", "flex-error/std"]
rpc-client = ["tokio", "rust-crypto", "cometbft-rpc/http-client"]
rust-crypto = ["cometbft/rust-crypto", "cometbft-light-client-verifier/rust-crypto"]
secp256k1 = ["cometbft/secp256k1", "cometbft-rpc/secp256k1"]
lightstore-sled = ["sled"]
unstable = ["rust-crypto"]
# Enable to execute long-running model-based tests
mbt = ["rust-crypto"]

[dependencies]
cometbft = { version = "0.34.0", path = "../cometbft", default-features = false }
cometbft-rpc = { version = "0.34.0", path = "../rpc", default-features = false }
cometbft-light-client-verifier = { version = "0.34.0", path = "../light-client-verifier", default-features = false }

contracts = { version = "0.6.2", default-features = false }
crossbeam-channel = { version = "0.4.2", default-features = false }
derive_more = { version = "0.99.5", default-features = false, features = ["display"] }
futures = { version = "0.3.4", default-features = false }
serde = { version = "1.0.106", default-features = false }
serde_cbor = { version = "0.11.1", default-features = false, features = ["alloc", "std"] }
serde_derive = { version = "1.0.106", default-features = false }
sled = { version = "0.34.3", optional = true, default-features = false }
static_assertions = { version = "1.1.0", default-features = false }
time = { version = "0.3", default-features = false, features = ["std"] }
tokio = { version = "1.0", default-features = false, features = ["rt"], optional = true }
flex-error = { version = "0.4.4", default-features = false }
tracing = { version = "0.1", default-features = false }
serde_json = { version = "1.0.51", default-features = false }
regex = { version = "1.7.3" }

[dev-dependencies]
cometbft-testgen = { path = "../testgen", default-features = false }

serde_json = { version = "1.0.51", default-features = false }
gumdrop = { version = "0.8.0", default-features = false }
rand = { version = "0.7.3", default-features = false }
tempfile = { version = "3.2.0", default-features = false }
proptest = { version = "0.10.1", default-features = false, features = ["std"] }
