[package]
name = "abci-test"
authors = ["Informal Systems <hello@informal.systems>"]
edition = "2021"
license = "Apache-2.0"
publish = false
description = """
    abci-test provides some end-to-end integration testing between
    cometbft-abci and a full CometBFT node.
    """

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flex-error = { version = "0.4.4", default-features = false, features = ["std"] }
futures = "0.3"
structopt = "0.3"
cometbft = { version = "0.1.0-alpha.2", path = "../../cometbft" }
cometbft-config = { version = "0.1.0-alpha.2", path = "../../config" }
cometbft-rpc = { version = "0.1.0-alpha.2", path = "../../rpc", features = [ "websocket-client" ] }
tracing = "0.1"
tracing-subscriber = "0.2"
tokio = { version = "1.20", features = ["full"] }
