[package]
name       = "cometbft-rpc-probe"
version    = "0.34.0"
authors    = ["Informal Systems <hello@informal.systems>"]
edition    = "2021"
license    = "Apache-2.0"
homepage   = "https://cometbft.com/"
repository = "https://github.com/cometbft/cometbft-rs"
readme     = "README.md"

description = """
    cometbft-rpc-probe allows us to probe a running CometBFT instance with
    a given sequence of requests, capturing those requests and/or responses.
    """

[package.metadata.docs.rs]
all-features = true

[dependencies]
async-tungstenite = { version = "0.17", features = [ "tokio-runtime", "tokio-rustls-native-certs" ] }
futures = "0.3"
getrandom = "0.2"
log = "0.4"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
simple_logger = "2"
structopt = "0.3"
subtle-encoding = "0.5"
thiserror = "1.0"
tokio = { version = "1.20", features = [ "full" ] }
uuid = "0.8"
