[env]
CONTAINER_NAME = "kvstore-test"
DOCKER_IMAGE = "informaldev/cometbft:0.34.21"
HOST_RPC_PORT = 26657
CARGO_MAKE_WAIT_MILLISECONDS = 1000
RUST_LOG = "debug"

[tasks.default]
clear = true
dependencies = [ "docker-up", "wait", "test", "docker-down" ]

[tasks.docker-down]
dependencies = [ "docker-stop", "docker-rm" ]

[tasks.docker-up]
command = "docker"
args = ["run", "--name", "${CONTAINER_NAME}", "--rm", "--publish", "26657:${HOST_RPC_PORT}", "--detach", "${DOCKER_IMAGE}"]
dependencies = ["docker-up-stop-old", "docker-up-rm-old"]

[tasks.test]
args = ["test", "--all-features", "--", "--nocapture", "--test-threads=1"]

[tasks.docker-stop]
command = "docker"
args = ["stop", "${CONTAINER_NAME}"]
ignore_errors = true
private = true

[tasks.docker-rm]
command = "docker"
args = ["rm", "--force", "${CONTAINER_NAME}"]
ignore_errors = true
private = true

[tasks.docker-up-stop-old]
alias = "docker-stop"

[tasks.docker-up-rm-old]
alias = "docker-rm"
