name: Build
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - main
      - 'v*.*.*'
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build-all

  build-light-client-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: cargo build-wasm-cometbft
      - run: cargo build-wasm-light-client

  tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build-tools

  # As per https://github.com/informalsystems/tendermint-rs/issues/1014
  generated-protos-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install protoc
        run: |
          curl -Lo /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip
          unzip /tmp/protoc.zip -d ${HOME}/.local
          echo "PROTOC=${HOME}/.local/bin/protoc" >> $GITHUB_ENV
          export PATH="${PATH}:${HOME}/.local/bin"
      - name: Install buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/download/v1.24.0/buf-Linux-x86_64 \
            -o /usr/local/bin/buf
          chmod +x /usr/local/bin/buf
      - name: Regenerate proto definitions
        working-directory: ./tools/proto-compiler/
        run: cargo run
      - name: Show the differences with checked-in files
        run: git diff -- proto/src/prost
      - name: Ensure that generated proto definitions compile
        run: cargo build-all
