name: Test
on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - main
      - 'v*.*.*'
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  default-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test

  # TODO(shonfeder): remove duplication once GitHub addresses one of these
  #  - https://github.community/t/support-for-yaml-anchors/16128/15
  #  - https://github.community/t/reusing-sharing-inheriting-steps-between-jobs-declarations/16851/13
  #  - https://github.community/t/using-matrix-variable-in-docker-image-name/17296
  cometbft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-all-features -p cometbft

  cometbft-rpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-all-features -p cometbft-rpc

  cometbft-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-all-features -p cometbft-proto

  cometbft-light-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      # NOTE: We test with default features to make sure things work without "unstable".
      - name: Test with default features
        run: cargo test -p cometbft-light-client
      - name: Test with all features
        run: cargo test-all-features -p cometbft-light-client

  # From https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/continuous-integration.html#github-actions
  cometbft-light-client-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wasm-pack test --headless --chrome ./light-client-js/
      - run: wasm-pack test --headless --firefox ./light-client-js/

  cometbft-testgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-all-features -p cometbft-testgen

  kvstore-integration-stable:
    runs-on: ubuntu-latest
    services:
      tendermint:
        image: informaldev/tendermint:0.34.21
        ports:
          - 26656:26656
          - 26657:26657
          - 26660:26660
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test-all-features --manifest-path tools/kvstore-test/Cargo.toml -- --nocapture
        env:
          RUST_LOG: debug

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - run: cargo test-all-features
        env:
          RUSTFLAGS: '-C instrument-coverage -C link-dead-code'
          LLVM_PROFILE_FILE: '%p-%m.profraw'
      - name: Install grcov
        run: |
          curl -L https://github.com/mozilla/grcov/releases/download/v0.8.18/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
      - name: Run grcov
        run: |
          ./grcov . --source-dir . --binary-path ./target/debug/ --output-type lcov --output-path ./lcov.info --branch --ignore-not-existing
      - name: Upload to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -f ./lcov.info
